stages:
  - build
  # - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

.tags: &tags
  tags:
    - chm

.before: &before
  before_script:
    - docker login --username ${REGISTERY_USERNAME} --password ${REGISTERY_PASSWORD} docker.gitlab.gwdg.de

.services: &services
  services:
    - name: "docker:18.09.0-dind"
      alias: docker

.commonheader: &commonheader
  <<: *services
  <<: *tags
  <<: *before

build:
  stage: build
  image: "docker:18.09.0"
  <<: *commonheader
  script:
    - docker build -f deployment/Dockerfile.mb -t docker.gitlab.gwdg.de/mpib/chm/mac/machine_culture_machines/catwell:latest .
    - docker push docker.gitlab.gwdg.de/mpib/chm/mac/machine_culture_machines/catwell:latest
    - docker run docker.gitlab.gwdg.de/mpib/chm/mac/machine_culture_machines/catwell:latest /start.sh start-catwell 
    - curl --request POST --url http://0.0.0.0:8085/eval --header 'content-type: application/json' --data '{"requestId": "asdasdasd","data": {"action": {"x": 0.2,"y": 0.3},"environment": {"type": "catwell","version": "foo","experimentName": "test","seed": 1}}}'


# TODO: deploy image
# run image with command: /start.sh start-catwell
# app is listening on port: 8085
# see also: deploymment/docker-compose.yml


# deploy:
#   stage: deploy
#   <<: *commonheader
#   image: docker.gitlab.gwdg.de/mpib/chm/mac/machine-culture-empirica/emperica:latest
#   script:
#     - aws --region eu-central-1 eks update-kubeconfig --name chm-test-default --region eu-central-1
#     - cat ~/.kube/config
#     - kubectl get ns
#     - helm upgrade --install empericaapp deployment/charts/Machines

