stages:
  - build-container
  - build

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

.tags: &tags
  tags:
    - chm

.before: &before
  before_script:
    - docker login --username ${REGISTERY_USERNAME} --password ${REGISTERY_PASSWORD} docker.gitlab.gwdg.de

.services: &services
  services:
    - name: "docker:18.09.0-dind"
      alias: docker

.commonheader: &commonheader
  <<: *services
  <<: *tags
  <<: *before

build-container:
  stage: build-container
  image: "docker:18.09.0"
  <<: *commonheader
  script:
    - docker build -f buildcontainer.dockerfile -t docker.gitlab.gwdg.de/mpib/chm/mac/machine-culture-empirica/emperica:latest .
    - docker push docker.gitlab.gwdg.de/mpib/chm/mac/machine-culture-empirica/emperica:latest

build:
  stage: build
  <<: *commonheader
  image: docker.gitlab.gwdg.de/mpib/chm/mac/machine-culture-empirica/emperica:latest
  script:
    - aws --region eu-central-1 eks update-kubeconfig --name chm-test-default --region eu-central-1
    - cat ~/.kube/config
    - kubectl get ns
    - npm run pull:submodules
    - npm run build
    - npm run docker:build
    - helm upgrade --install empericaapp charts/EmpericaApp
