PUT http://3.122.195.208/config
content-type: application/yaml

- name: Human
  parameter:
    gamma_s: 0.4
    gamma_g: 0.2
    beta: 0.01
  type: pruning
- name: Risky
  parameter:
    gamma_s: 0.4
    gamma_g: 0.2
    beta: 0.01
  type: pruning
- name: Lookahead
  parameter:
    gamma_s: 0.0
    gamma_g: 0.0
    beta: null
  type: pruning