PUT http://3.122.195.208/config
content-type: application/yaml

- name: Human
  parameter:
    gamma_s: 0.564
    gamma_g: 0.355
    beta: 0.0142
  type: pruning
- name: Risky
  parameter:
    gamma_s: 0.225
    gamma_g: 0.336
    beta: 0.0142
  type: pruning
- name: Neutral
  parameter:
    gamma_s: 0.351
    gamma_g: 0.351
    beta: 0.0142
  type: pruning
- name: Lookahead
  parameter:
    gamma_s: 0.0
    gamma_g: 0.0
    beta: null
  type: pruning
- name: NoPlan
  parameter:
    gamma_s: 1.
    gamma_g: 1.
    beta: null
  type: pruning
- name: Random
  type: random