apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: Machines
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: 'machinesapp.eks-test-default.mpg-chm.com'
      http:
        paths:
          - backend:
              serviceName: Machines
              servicePort: http
            path: /
  tls:
    - hosts:
        - 'machinesapp.eks-test-default.mpg-chm.com'
