---
apiVersion: v1
kind: Service
metadata:
  name: Machines
  labels:
    app.kubernetes.io/name: {{ include "Machines.name" . }}
    helm.sh/chart: {{ include "Machines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: listener
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "Machines.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None