--- # ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: machine-culture-v3-machine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: machine-culture-v3-machine
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.9
          imagePullPolicy: Always
          name: machine-culture-v3-machine
          ports:
            - containerPort: 8080
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: machine-culture-v3-machine
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: machine-culture-v3-machine
#     spec:
#       containers:
#         - image: levinb/machine-culture:0fae4e55f8304fbfbb2688213db265c6c435e0a7
#           imagePullPolicy: Always
#           # imagePullPolicy: IfNotPresent
#           name: machine-culture-v3-machine-container
#           ports:
#             - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: machine-culture-v3-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: machine-culture-v3-machine
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: machine-culture-v3-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - machine-culture-v3.eks-test-default.mpg-chm.com
  rules:
    - host: machine-culture-v3.eks-test-default.mpg-chm.com
      http:
        paths:
          - path: /
            backend:
              serviceName: machine-culture-v3-service
              servicePort: 80
