--- # ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: machine-culture-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: machine-culture-v1
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.9
          imagePullPolicy: Always
          name: machine-culture-v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: machine-culture-v1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: machine-culture-v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: machine-culture-v1
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - machine-culture-v1.eks-test-default.mpg-chm.com
  rules:
    - host: machine-culture-v1.eks-test-default.mpg-chm.com
      http:
        paths:
          - path: /
            backend:
              serviceName: machine-culture-v1
              servicePort: 80
