#!/usr/bin/env bash

curl --request POST --url http://0.0.0.0:8085/eval --header 'content-type: application/json' --data '{"requestId": "asdasdasd","data": {"action": {"x": 0.2,"y": 0.3},"environment": {"type": "catwell","version": "foo","experimentName": "test","seed": 1}}}'